In [3]:
import numpy as np

In [4]:
def make_slices_2d(data, win_size):
    """
    Adapted from cgarrad's geoprocessing book
    Return a list of slices given a window size
    :param data: 2D array to get slices from
    :param win_size: tuple of (rows, columns) for the moving window
    :return: list of slices
    """
    # Calculate the size of the slice
    rows = data.shape[0] - win_size[0] + 1
    cols = data.shape[1] - win_size[1] + 1
    slices = []
    for i in range(win_size[0]):  # construct the slices
        for j in range(win_size[1]):
            slices.append(data[i:rows + i, j:cols + j])
    return slices

In [46]:
data = np.arange(1,37).reshape(6,6)

In [47]:
# for sl in slices:
#     print(sl)
#     print()

In [48]:
data

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [61]:
result = np.where(data==8)
listOfCoordinates= list(zip(result[0], result[1]))
listOfCoordinates

[(1, 1)]

[(3, 3)]

In [36]:
data[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [51]:
data[3,3]

22

In [68]:
def slice_by_window(data, px_x, px_y, window_size):
    """"""
    step = (window_size - 1)//2
    row_start = px_x - step
    row_stop = px_x + step + 1
    col_start = px_y - step
    col_stop = px_y + step + 1
    res = data[row_start:row_stop, col_start:col_stop]
    if res.shape[0] * res.shape[1] != window_size * window_size:
        return
    return res

In [74]:
res = slice_by_window(data, 2, 2, 3)

In [76]:
res.mean()

15.0

In [77]:
res

array([[ 8,  9, 10],
       [14, 15, 16],
       [20, 21, 22]])